### ISSUE TITLE
Icon not show in notifications

### ISSUE THREAD

**Issue by mauri870** [devfake/cloudradioo#10]
I don't know why but the icon does not appear in the web notifications... Locally it works fine

As you can see the other images works (obviously)
![captura de tela de 2016-07-18 08-58-04](https://cloud.githubusercontent.com/assets/10168637/16914094/d19cc572-4cc5-11e6-8ed4-be1b8c839eef.png)

**Comment by devfake** [comment]
Sorry, my fault. I forgot to upload the icon :|
