### ISSUE TITLE
Error running gulp

### ISSUE THREAD

**Issue by mauri870** [devfake/cloudradioo#3]
The last line on gulpfile throws an error during gulp execution

```
mix.task('browserify', './app/**/**.vue');
```

Commenting this line the error not show.

You have another solution for this?

**Comment by devfake** [comment]
Yeah, the error throws only if you run `gulp` or `gulp --production`. Try to run `gulp watch` or `gulp watch --production`. I'm not exactly sure why this doesn't work :|

**Comment by mauri870** [comment]
This line is necessary for the application?
Because I remove then and the app works fine

**Comment by devfake** [comment]
No :) If this line is removed, `gulp watch` will not triggered if we change an .vue file. But you can manually run `gulp`  after an change.

**Comment by mauri870** [comment]
I try here and the watch is triggered on modify vue files :/
I'm using linux

**Comment by devfake** [comment]
Hm, maybe it's only on my build. Have you other problems?

**Comment by mauri870** [comment]
See #4 ;)
