### ISSUE TITLE
Notifications for the web version

### ISSUE THREAD

**Issue by mauri870** [devfake/cloudradioo#7]
What  you think of implementing the html5 notifications to the web version?
Also create a store module named app for example is needed for store some settings for the web app scope, like apiKey and notification settings (on /off  etc) and other settings that come in the future because that goes beyond the responsability of player store module
I look forward to your reply, thanks

**Comment by devfake** [comment]
I think notifications would not be bad :) After few e2e tests, i can start with the them (If you have not already started).

For the settings i actually planned to use the `options` module. I'm in the middle of the work for the repeat function, and restructured the modules a bit.

**Comment by mauri870** [comment]
Notifications can be implemented by adapting the app version because both use html5, 
we need only ask to user if we can show notifications (on electron it is enabled by default)
