### ISSUE TITLE
Vue and Vuex 2.0

### ISSUE THREAD

**Issue by mauri870** [devfake/cloudradioo#9]
Vue and Vuex 2.0 are currently in RC, you have plans for migrate cloudradioo to this new version?
Has some breaking changes with Vuex, like the deprecation of vuex inside components

[Vuex 2.0 ](https://github.com/vuejs/vuex/issues/236)
[Vue 2.0](https://github.com/vuejs/vue/issues/2873)

**Comment by devfake** [comment]
I have been following the changes and the discussions for vue and vuex, and i will definitely migrate cloudradioo to version 2.0. 

However, I have currently very little time to work on cloudradioo (Again, thank you for the notify pull request!).
